app = "your-vpn-name" # change this to a unique name

[build]
dockerfile = "./Dockerfile"

[env]
PASSWORD = "strong-password"    # change this to a secure VPN password
METHOD = "aes-256-gcm"          # encryption method

[[services]]
internal_port = 8388
protocol = "tcp"

  [[services.ports]]
  port = 8388
